PROCDICT = (
    ('aboveThreshold', 'Відкриті торги з особливостями'),
    ('aboveThresholdUA','Відкриті торги'),
    ('aboveThresholdEU','Відкриті торги (EU)'),
    ('belowThreshold','Спрощена закупівля'),
    ('negotiation','Переговорна процедура'),
    ('negotiation.quick','Переговорна процедура (за нагальною потребою)'),
    ('reporting','Звіт про договір'),
    ('esco','Закупівля енергосервісу'),
    ('competitiveDialogue','Конкурентний діалог'),
    ('competitiveOrdering', 'Конкурентна заявка'),
    ('competitiveDialogueUA','Конкурентний діалог (UA)'),
    ('competitiveDialogueEU','Конкурентний діалог (EU)'),
    ('priceQuotation','Запит ціни пропозицій'),
    ('competitiveDialogue.stage2','Конкурентний діалог, 2 етап'),
    ('competitiveDialogueEU.stage2','Конкурентний діалог (EU), 2 етап'),
    ('competitiveDialogueUA.stage2','Конкурентний діалог (UA), 2 етап'),
    ('aboveThresholdUA.defense','Закупівля для потреб оборони'),
    ('closeFrameworkAgreementUA','Укладання рамкової угоди'), 
    ('simple.defense', 'Спрощені торги для гарантованого забезпечення потреб безпеки і оборони'),
    ('closeFrameworkAgreementSelectionUA','Відбір для закупівлі за рамковою угодою'),
)

STATUSDICT = (
 ('reporting.active','Активний тендер (за умовчанням)'),
 ('reporting.complete','Завершений тендер'),
 ('reporting.cancelled','Відмінена закупівля (відмінена)'),
 ('reporting.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('aboveThresholdUA.defense.active.tendering','Очікування пропозицій (пропозиції)'),
 ('aboveThresholdUA.defense.active.auction','Період аукціону (аукціон)'),
 ('aboveThresholdUA.defense.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('aboveThresholdUA.defense.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('aboveThresholdUA.defense.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('aboveThresholdUA.defense.complete','Завершена закупівля (завершена)'),
 ('aboveThresholdUA.defense.cancelled','Відмінена закупівля (відмінена)'),
 ('aboveThresholdUA.active.tendering','Очікування пропозицій (пропозиції)'),
 ('aboveThresholdUA.active.auction','Період аукціону (аукціон)'),
 ('aboveThreshold.active.tendering', 'Подання пропозицій'),
 ('aboveThresholdUA.active.tendering', 'Подання пропозицій'),
 ('aboveThresholdUA.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('aboveThresholdUA.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('aboveThresholdUA.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('aboveThresholdUA.complete','Завершена закупівля (завершена)'),
 ('aboveThresholdUA.cancelled','Відмінена закупівля (відмінена)'),
 ('competitiveDialogueUA.active.tendering','Очікування пропозицій (пропозиції)'),
 ('competitiveDialogueUA.active.auction','Період аукціону (аукціон)'),
 ('competitiveDialogueUA.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('competitiveDialogueUA.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('competitiveDialogueUA.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('competitiveDialogueUA.complete','Завершена закупівля (завершена)'),
 ('competitiveDialogueUA.cancelled','Відмінена закупівля (відмінена)'),
 ('esco.active.tendering','Період подання пропозицій та уточнень'),
 ('esco.active.pre-qualification','Перед-кваліфікаційний період'),
 ('esco.active.pre-qualification.stand-still','Блокування перед аукціоном'),
 ('esco.active.auction','Період аукціону (аукціон)'),
 ('esco.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('esco.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('esco.complete','Завершена закупівля (завершена)'),
 ('esco.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('esco.cancelled','Відмінена закупівля (відмінена)'),
 ('aboveThresholdEU.active.tendering','Період подання пропозицій та уточнень'),
 ('aboveThresholdEU.active.pre-qualification','Перед-кваліфікаційний період'),
 ('aboveThresholdEU.active.pre-qualification.stand-still','Блокування перед аукціоном'),
 ('aboveThresholdEU.active.auction','Період аукціону (аукціон)'),
 ('aboveThresholdEU.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('aboveThresholdEU.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('aboveThresholdEU.complete','Завершена закупівля (завершена)'),
 ('aboveThresholdEU.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('aboveThresholdEU.cancelled','Відмінена закупівля (відмінена)'),
 ('competitiveDialogueEU.active.tendering','Період подання пропозицій та уточнень'),
 ('competitiveDialogueEU.active.pre-qualification','Перед-кваліфікаційний період'),
 ('competitiveDialogueEU.active.pre-qualification.stand-still','Блокування перед аукціоном'),
 ('competitiveDialogueEU.active.auction','Період аукціону (аукціон)'),
 ('competitiveDialogueEU.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('competitiveDialogueEU.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('competitiveDialogueEU.complete','Завершена закупівля (завершена)'),
 ('competitiveDialogueEU.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('competitiveDialogueEU.cancelled','Відмінена закупівля (відмінена)'),
 ('closeFrameworkAgreementUA.active.tendering','Очікування пропозицій (пропозиції)'),
 ('closeFrameworkAgreementUA.active.pre-qualification','Пре-кваліфікаційній період (пре-кваліфікація)'),
 ('closeFrameworkAgreementUA.active.pre-qualification.stand-still','Блокування перед аукціоном'),
 ('closeFrameworkAgreementUA.active.auction','Період аукціону (аукціон)'),
 ('closeFrameworkAgreementUA.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('closeFrameworkAgreementUA.active.qualification.stand-still','Standstill before contract signing'),
 ('closeFrameworkAgreementUA.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('closeFrameworkAgreementUA.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('closeFrameworkAgreementUA.complete','Завершена закупівля (завершена)'),
 ('closeFrameworkAgreementUA.cancelled','Відмінена закупівля (відмінена)'),
 ('closeFrameworkAgreementSelectionUA.draft','ProcuringEntity creats draft of procedure, where should be specified procurementMethodType - closeFrameworkAgreementSelectionUA, procurementMethod - selective. One lot structure procedure. Also ProcuringEntity should specify agreement: id, items, title, description and features, if needed.'),
 ('closeFrameworkAgreementSelectionUA.draft.pending','ProcuringEntity changes status of procedure from „draft“ to „draft.pending“ to make the system check provided information and pull up necassery information from Agreement in cfaua.'),
 ('closeFrameworkAgreementSelectionUA.draft.unsuccessful','Terminal status. System moves procedure to „draft.unsuccessful“ status if at least one of the checks is failed.'),
 ('closeFrameworkAgreementSelectionUA.active.enquiries','Період уточнень (уточнення)'),
 ('closeFrameworkAgreementSelectionUA.active.tendering','Очікування пропозицій (пропозиції)'),
 ('closeFrameworkAgreementSelectionUA.active.auction','Період аукціону (аукціон)'),
 ('closeFrameworkAgreementSelectionUA.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('closeFrameworkAgreementSelectionUA.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('closeFrameworkAgreementSelectionUA.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('closeFrameworkAgreementSelectionUA.complete','Завершена закупівля (завершена)'),
 ('closeFrameworkAgreementSelectionUA.cancelled','Відмінена закупівля (відмінена)'),
 ('aboveThresholdUA.defense.active.enquiries','Період уточнень (уточнення)'),
 ('aboveThresholdUA.defense.active.tendering','Очікування пропозицій (пропозиції)'),
 ('aboveThresholdUA.defense.active.auction','Період аукціону (аукціон)'),
 ('aboveThresholdUA.defense.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('aboveThresholdUA.defense.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('aboveThresholdUA.defense.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('aboveThresholdUA.defense.complete','Завершена закупівля (завершена)'),
 ('aboveThresholdUA.defense.cancelled','Відмінена закупівля (відмінена)'),
 ('belowThreshold.active.enquiries','Період уточнень (уточнення)'),
 ('belowThreshold.active.tendering','Очікування пропозицій (пропозиції)'),
 ('belowThreshold.active.auction','Період аукціону (аукціон)'),
 ('belowThreshold.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('belowThreshold.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('belowThreshold.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('belowThreshold.complete','Завершена закупівля (завершена)'),
 ('belowThreshold.cancelled','Відмінена закупівля (відмінена)'),
 ('negotiation.active.enquiries','Період уточнень (уточнення)'),
 ('negotiation.active.tendering','Очікування пропозицій (пропозиції)'),
 ('negotiation.active.auction','Період аукціону (аукціон)'),
 ('negotiation.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('negotiation.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('negotiation.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('negotiation.complete','Завершена закупівля (завершена)'),
 ('negotiation.cancelled','Відмінена закупівля (відмінена)'),
 ('negotiation.quick.active.enquiries','Період уточнень (уточнення)'),
 ('negotiation.quick.active.tendering','Очікування пропозицій (пропозиції)'),
 ('negotiation.quick.active.auction','Період аукціону (аукціон)'),
 ('negotiation.quick.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('negotiation.quick.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('negotiation.quick.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('negotiation.quick.complete','Завершена закупівля (завершена)'),
 ('negotiation.quick.cancelled','Відмінена закупівля (відмінена)'),
 ('competitiveDialogue.active.enquiries','Період уточнень (уточнення)'),
 ('competitiveDialogue.active.tendering','Очікування пропозицій (пропозиції)'),
 ('competitiveDialogue.active.auction','Період аукціону (аукціон)'),
 ('competitiveDialogue.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('competitiveDialogue.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('competitiveDialogue.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('competitiveDialogue.complete','Завершена закупівля (завершена)'),
 ('competitiveDialogue.cancelled','Відмінена закупівля (відмінена)'),
 ('competitiveDialogue.stage2.active.enquiries','Період уточнень (уточнення)'),
 ('competitiveDialogue.stage2.active.tendering','Очікування пропозицій (пропозиції)'),
 ('competitiveDialogue.stage2.active.auction','Період аукціону (аукціон)'),
 ('competitiveDialogue.stage2.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('competitiveDialogue.stage2.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('competitiveDialogue.stage2.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('competitiveDialogue.stage2.complete','Завершена закупівля (завершена)'),
 ('competitiveDialogue.stage2.cancelled','Відмінена закупівля (відмінена)'),
 ('priceQuotation.active.enquiries','Період уточнень (уточнення)'),
 ('priceQuotation.active.tendering','Очікування пропозицій (пропозиції)'),
 ('priceQuotation.active.auction','Період аукціону (аукціон)'),
 ('priceQuotation.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('priceQuotation.active.awarded','Пропозиції розглянуто (розглянуто)'),
 ('priceQuotation.unsuccessful','Закупівля не відбулась (не відбулась)'),
 ('priceQuotation.complete','Завершена закупівля (завершена)'),
 ('priceQuotation.cancelled','Відмінена закупівля (відмінена)'),
 ('simple.defense.active.qualification','Кваліфікація переможця (кваліфікація)'),
 ('simple.defense.active.tendering','Очікування пропозицій (пропозиції)'),
)
